### ISSUE TITLE
Project structure redundant root folder

### ISSUE THREAD

**Issue by pabl0xf** [martincho111986/vet-puercoArania-BE#21]
![image](https://user-images.githubusercontent.com/6700982/89737831-1770bc80-da29-11ea-900c-d8366b98b57e.png)

El proyect ya es de backend, tener otra carpeta llamada backend es redudante y lo esperado en la raiz del proyecto es package.json y lo necesario para hacer el setup

**Comment by martincho111986** [comment]
Si, me di cuenta después que lo envíe que lo había dejado asi, la idea era
armar una carpeta donde este el Frontend y el backend por eso, gracias por
avisarme

**Comment by martincho111986** [comment]
ya fue resuelto pablo
