### ISSUE TITLE
Install error, and redundant folders

### ISSUE THREAD

**Issue by fabriziotonin** [martincho111986/vet-puercoArania-BE#23]
Después de seguir los pasos e instalar npm install e nodemon no se ejecuta error
![image](https://user-images.githubusercontent.com/51201108/91885444-27617200-ec5e-11ea-83b8-f8f2d43942a3.png)

- TypeError: JwtStrategy requires a secret or key

**Comment by martincho111986** [comment]
ya fue resuelto, te deje en el example.env los datos de las variables de entorno
